# Generated by Django 4.2.5 on 2023-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_backend_frontend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='image',
            field=models.ImageField(upload_to='portfolio/backend/'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='image',
            field=models.ImageField(upload_to='portfolio/frontend/'),
        ),
    ]
